### ISSUE TITLE
How can I remove the auxiliary line?

### ISSUE THREAD

**Issue by HazySoda** [avaneeshtripathi/react-dice-roll#6]
![image](https://user-images.githubusercontent.com/16027183/112800837-c2aab080-90a2-11eb-8677-6c48f3102a0e.png)

There are some auxiliary lines after the component is rendered. How can I remove them? thank you very much.

**Comment by avaneeshtripathi** [comment]
Hi @HazySoda,
These were the box-shadow that were missed out. In the newer version 1.2.2, these lines are removed.
