### ISSUE TITLE
External dice roll triggers

### ISSUE THREAD

**Issue by ianleblancbomb** [avaneeshtripathi/react-dice-roll#9]
Not an issue per say but would be nice to trigger dice roll externally from clicking on dice so multiple dice on screen can all be triggered at once.

**Comment by Rakeshpradhan1999** [comment]
I also want this function

**Comment by avaneeshtripathi** [comment]
@ianleblancbomb @Rakeshpradhan1999 
To achieve this,
You can pass refs to the dice components, and use that ref to trigger the dice roll

Ex: diceRef.rollDice()

this method can be used, its not typescripted though. But it does work.

for multiple dices, you can pass refs to all the dices and then trigger rollDice for all of them.
